name: recipe-book-bot
services:
  mongo:
    image: mongo:5.0.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  memcached:
    image: memcached:1.6.21
    restart: always
    ports:
      - "11211:11211"